package com.example.finwise.util

object Routes {
    const val LoginScreen = "loginScreen"
    const val onBoardingScreen = "onBoardingscreen"
    const val LoginScreen2 = "loginScreen2"
    const val SignupScreen = "signupScreen"
    const val ForgetPasswordScreen = "forgetPasswordScreen"
    const val HomeScreen = "homeScreen"
    const val AnalysisScreen = "analysisScreen"
    const val ProfileScreen = "profileScreen"
    const val TransactionScreen = "transactionScreen"
    const val AccountBalanceScreen = "accountBalanceScreen"
    const val ExpenseScreen = "expenseScreen"
    const val CategoryScreen = "categoryScreen"
    const val NotificationScreen = "notificationScreen"
    const val FoodCategoryScreen = "foodCategoryScreen"
    const val EntertainmentCategoryScreen = "entertaimentCategoryScreen"
    const val TransportCategoryScreen = "transportCategoryScreen"
    const val MedicineCategoryScreen = "medicineCategoryScreen"
    const val SavingsCategoryScreen = "savingsCategoryScreen"
    const val GroceriesCategoryScreen = "groceriesCategoryScreen"
    const val RentCategoryScreen = "rentCategoryScreen"
    const val GiftsCategoryScreen = "giftsCategoryScreen"
    const val AddExpenseScreen = "addExpenseScreen"
    const val AddIncomeScreen = "addIncomeScreen"
    const val FoodDetailScreen = "foodDetailScreen"
    const val CarSavingsScreen = "carSavingsScreen"
    const val HomeSavingsScreen = "homeSavingsScreen"
    const val WeddingSavingsScreen = "weddingSavingsScreen"
    const val TravelSavingsScreen = "travelSavingsScreen"
    const val EditProfileScreen = "editProfileScreen"
    const val EMPTY_STRING = ""
}